### ISSUE TITLE
Hello from Heroku

### ISSUE THREAD

**Issue by schneems** [barsoom/devbook#34]
> Do more research into what Heroku does exactly.

I maintain the Heroku Ruby buildpack. We don't do anything with migrations. Auto running migrations on deploy could be pretty disastrous https://github.com/heroku/heroku-buildpack-ruby/pull/330#issuecomment-79452369 not just on Heroku, but anywhere really.

**Comment by henrik** [comment]
@schneems, thank you! Hello from Barsoom! Will update the document to reference this info, and if/when we move more code onto Heroku we'll see what we're comfortable doing.
